"""cascade delete server versions

Revision ID: 2f83755a3fd1
Revises: 7040e35c1223
Create Date: 2026-09-03 18:34:16.875142

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2f83755a3fd1"
down_revision: str | Sequence[str] | None = "7040e35c1223"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("mcp_server_versions_server_id_fkey"),
        "mcp_server_versions",
        type_="foreignkey",
    )
    op.create_foreign_key(
        None,
        "mcp_server_versions",
        "mcp_servers",
        ["server_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "mcp_server_versions", type_="foreignkey")
    op.create_foreign_key(
        op.f("mcp_server_versions_server_id_fkey"),
        "mcp_server_versions",
        "mcp_servers",
        ["server_id"],
        ["id"],
    )
    # ### end Alembic commands ###
