"""add connectivity status to mcp_serevers

Revision ID: ad6ab59e8d46
Revises: c572637eabfe
Create Date: 2026-09-03 20:56:26.517935

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ad6ab59e8d46"
down_revision: str | Sequence[str] | None = "c572637eabfe"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "mcp_servers",
        sa.Column(
            "connectivity_status", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
    )
    op.add_column(
        "mcp_servers",
        sa.Column("last_checked_at", sa.DateTime(timezone=True), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("mcp_servers", "last_checked_at")
    op.drop_column("mcp_servers", "connectivity_status")
    # ### end Alembic commands ###
